const canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d");
let W,H,score=0,level=1,speed=6,move=0,run=true;
let player={x:0,y:0,w:95,h:120},other={x:0,y:-160,w:85,h:105},coins=[],stuff=[];
function size(){W=canvas.width=innerWidth;H=canvas.height=innerHeight;player.y=H-155;player.x=W/2-player.w/2}size();addEventListener("resize",size);
function ri(){let rw=Math.min(W*.62,760);return{rw:rw,left:W/2-rw/2,right:W/2+rw/2}}
function cloud(x,y,s){ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(x,y,18*s,0,7);ctx.arc(x+24*s,y-9*s,26*s,0,7);ctx.arc(x+53*s,y,20*s,0,7);ctx.fill()}
function tree(x,y){ctx.fillStyle="#754221";ctx.fillRect(x-5,y,10,36);ctx.fillStyle="#2f9d47";ctx.beginPath();ctx.arc(x,y-12,26,0,7);ctx.arc(x-18,y,20,0,7);ctx.arc(x+18,y,20,0,7);ctx.fill()}
function house(x,y,s){ctx.fillStyle="#f5c85e";ctx.fillRect(x,y,s,s*.72);ctx.fillStyle="#e85a45";ctx.beginPath();ctx.moveTo(x-8,y);ctx.lineTo(x+s/2,y-s*.35);ctx.lineTo(x+s+8,y);ctx.fill();ctx.fillStyle="#7a4b25";ctx.fillRect(x+s*.4,y+s*.36,s*.2,s*.36);ctx.fillStyle="#9fe1ff";ctx.fillRect(x+s*.1,y+s*.2,s*.22,s*.2)}
function bg(){ctx.fillStyle="#64bfe9";ctx.fillRect(0,0,W,H);cloud(90,150,1);cloud(W*.75,180,.9);ctx.fillStyle="#78c94c";ctx.fillRect(0,H*.23,W,H);let r=ri();house(40,H*.32,110);house(W-180,H*.36,120);house(W*.18,H*.56,75);house(W*.78,H*.57,75);ctx.fillStyle="#555962";ctx.beginPath();ctx.moveTo(r.left,0);ctx.lineTo(r.right,0);ctx.lineTo(r.right+W*.22,H);ctx.lineTo(r.left-W*.22,H);ctx.fill();ctx.strokeStyle="#222";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(r.left,0);ctx.lineTo(r.left-W*.22,H);ctx.moveTo(r.right,0);ctx.lineTo(r.right+W*.22,H);ctx.stroke();ctx.fillStyle="#ffe23e";for(let y=-80+move;y<H;y+=115)ctx.fillRect(W/2-7,y,14,65);for(let y=80;y<H;y+=150){tree(r.left-65,y);tree(r.right+65,y+65)}}
function car(a,color,who){ctx.fillStyle="#202020";ctx.fillRect(a.x-7,a.y+24,13,28);ctx.fillRect(a.x+a.w-6,a.y+24,13,28);ctx.fillRect(a.x-7,a.y+76,13,28);ctx.fillRect(a.x+a.w-6,a.y+76,13,28);ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(a.x,a.y,a.w,a.h,15);ctx.fill();ctx.strokeStyle="#111";ctx.lineWidth=4;ctx.stroke();ctx.fillStyle="#ffcfae";ctx.beginPath();ctx.arc(a.x+a.w/2,a.y+35,25,0,7);ctx.fill();ctx.stroke();if(who=="motu"){ctx.fillStyle="#171717";ctx.beginPath();ctx.arc(a.x+a.w/2-13,a.y+48,13,0,7);ctx.arc(a.x+a.w/2+13,a.y+48,13,0,7);ctx.fill();ctx.fillStyle="#111";ctx.beginPath();ctx.arc(a.x+a.w/2-9,a.y+32,3,0,7);ctx.arc(a.x+a.w/2+9,a.y+32,3,0,7);ctx.fill()}else{ctx.strokeStyle="#111";ctx.lineWidth=3;ctx.strokeRect(a.x+a.w/2-20,a.y+25,15,12);ctx.strokeRect(a.x+a.w/2+5,a.y+25,15,12);ctx.beginPath();ctx.moveTo(a.x+a.w/2-5,a.y+31);ctx.lineTo(a.x+a.w/2+5,a.y+31);ctx.stroke();ctx.fillStyle="#222";ctx.fillRect(a.x+a.w/2-16,a.y+5,5,13);ctx.fillRect(a.x+a.w/2,a.y+3,5,15);ctx.fillRect(a.x+a.w/2+12,a.y+6,5,12)}ctx.fillStyle="#aeeaff";ctx.fillRect(a.x+12,a.y+70,a.w-24,17)}
function coin(o){ctx.fillStyle="#ffbd1c";ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,7);ctx.fill();ctx.strokeStyle="#fff16b";ctx.lineWidth=5;ctx.beginPath();ctx.arc(o.x,o.y,o.r-5,0,7);ctx.stroke()}
function cone(o){ctx.fillStyle="#ff7138";ctx.beginPath();ctx.moveTo(o.x,o.y-o.h/2);ctx.lineTo(o.x-o.w/2,o.y+o.h/2);ctx.lineTo(o.x+o.w/2,o.y+o.h/2);ctx.fill();ctx.fillStyle="#fff";ctx.fillRect(o.x-o.w*.27,o.y,o.w*.54,o.h*.14);ctx.fillStyle="#222";ctx.fillRect(o.x-o.w*.65,o.y+o.h/2-6,o.w*1.3,12)}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function spawn(){let r=ri(),l=r.left+50,q=r.right-50;coins.push({x:l+Math.random()*(q-l),y:-30,r:20});if(Math.random()<.45)stuff.push({x:l+Math.random()*(q-l),y:-80,w:50,h:75})}
function over(){run=false;document.getElementById("final").textContent=score;document.getElementById("over").style.display="flex"}
function update(){move+=speed;if(move>115)move=0;other.y+=speed;if(other.y>H+130){other.y=-160;let r=ri();other.x=r.left+45+Math.random()*(r.rw-other.w-90)}coins.forEach(o=>o.y+=speed);stuff.forEach(o=>o.y+=speed);coins=coins.filter(o=>{if(o.y>H+50)return false;if(player.x<o.x+o.r&&player.x+player.w>o.x-o.r&&player.y<o.y+o.r&&player.y+player.h>o.y-o.r){score++;document.getElementById("score").textContent=score;if(score%6===0){level++;speed+=.7;document.getElementById("level").textContent=level}return false}return true});stuff=stuff.filter(o=>{if(o.y>H+100)return false;if(hit(player,{x:o.x-o.w/2,y:o.y-o.h/2,w:o.w,h:o.h}))over();return true});if(hit(player,other))over();if(Math.random()<.018)spawn()}
function loop(){if(!run)return;bg();update();stuff.forEach(cone);coins.forEach(coin);car(other,"#8d54d8","patlu");car(player,"#e8443a","motu");requestAnimationFrame(loop)}
function mp(n){player.x+=n;let r=ri(),min=r.left-W*.18,max=r.right+W*.18-player.w;player.x=Math.max(min,Math.min(max,player.x))}
addEventListener("keydown",e=>{if(e.key=="ArrowLeft")mp(-35);if(e.key=="ArrowRight")mp(35);if(e.key=="ArrowUp"){player.y-=45;setTimeout(()=>player.y=H-155,180)}});document.getElementById("left").onclick=()=>mp(-35);document.getElementById("right").onclick=()=>mp(35);document.getElementById("jump").onclick=()=>{player.y-=45;setTimeout(()=>player.y=H-155,180)};canvas.addEventListener("touchmove",e=>{e.preventDefault();player.x=e.touches[0].clientX-player.w/2;mp(0)},{passive:false});loop();